version: 2

updates:         
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: '*'
        update-types: ["version-update:semver-patch"]

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: '*'
        update-types: ["version-update:semver-patch"]

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: '*'
        update-types: ["version-update:semver-patch"]
