# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4.4.0
      with:
        java-version: '21'
        distribution: 'zulu'
        cache: 'maven'
    - name: Build with Maven
      run: mvn --batch-mode --strict-checksums verify
